from django.urls import path
from .views import plantilla
from .api.viewsets import (
    PersonaListar,
    PersonaCrear,
    PersonaDetalle,
    PersonaEliminar,
    PersonaBuscar,
    RegistroCrear,
    current_user,
    GenericaListar,
    GenericaCrear,
    GenericaEliminar,
    PersonaGenericaBuscar,
    # ValidarCredenciales,
    PermisosPerfil,
    GenericaListarPersonaSesion,
    DatosPersona,
    GenericaDetalle,
    PersonaCambiarPass,
    GenericasValoresPermisoPersona,
    EliminarGenericaPermiso,
    ProgramasUsuario,
    CrearMasivos,
    DatosPersonaApp,
    ActualizarCodigosQr,
    CrearCodigosQr,
    buscarIdentidades,
    CrearBarracode,
    RolesPersona,
    PermisosPerfilSubmodulos,
    fotoMs,
    EncuestaSPA,
    ObtenerEncuestaGenero,
    ValidarEncuestaGenero,
    GuardarEncuestaGenero,
    ValidarCredencialesNew,
    MicrosoftTokenValidator,
    ValidarCredencialesNewApp,
    ValidarPolitica,
    AceptarPolitica
)


urlpatterns = [
    path("current_user", current_user),
    # path("validar_credenciales", ValidarCredenciales.as_view(), name=None),
    path("validar_credenciales", ValidarCredencialesNewApp.as_view(), name=None),
    path("validar_credenciales_ms", ValidarCredencialesNew.as_view(), name=None),
    path("microsoft/token/validate", MicrosoftTokenValidator.as_view(), name=None),
    path("personas", PersonaListar.as_view(), name=None),
    path("personas/crear", PersonaCrear.as_view(), name=None),
    path("personas/<int:pk>/eliminar", PersonaEliminar.as_view(), name=None),
    path("personas/<int:pk>/genericas/<int:tipo>",GenericaListar.as_view({"get": "list"}), name=None,),
    path("personas/genericas/<int:tipo>",GenericaListarPersonaSesion.as_view({"get": "list"}), name=None,),
    # path("personas/<int:pk>/genericas/areas",GenericaListarPersonasAreaInvestigacion.as_view({"get": "list"}), name=None,),
    path("personas/<int:pk>/genericas/crear", GenericaCrear.as_view(), name=None),
    path("personas/buscar", PersonaBuscar.as_view({"post": "list"}), name=None),
    path("personas/<int:pk>", PersonaDetalle.as_view(), name=None),
    path("personas/generica/<int:pk>", GenericaDetalle.as_view(), name=None),
    path("personas/generica/<int:pk>/eliminar", GenericaEliminar.as_view(), name=None),
    path("personas/generica/<int:tipo>/buscar", PersonaGenericaBuscar.as_view({"post": "list"}), name=None),
    path("plantilla", plantilla, name=None),
    path("personas/<int:pk>/genericas/permiso",PermisosPerfil.as_view({"get": "list"}),name=None,),
    path("personas/<int:pk>/genericas/permiso/<str:codigo>",PermisosPerfilSubmodulos.as_view({"get": "list"}),name=None,),
    path("personas/<int:pk>/datos",DatosPersona.as_view({"get": "list"}),name=None,),
    path("personas/<int:pk>/cambiar_pass", PersonaCambiarPass.as_view(), name=None),
    path("personas/<int:pk>/genericas/<int:tipo>/permiso", GenericasValoresPermisoPersona.as_view(), name=None),
    path("personas/<int:pk>/genericas/<int:val>/permiso/<int:tipo>/eliminar", EliminarGenericaPermiso.as_view(), name=None),
    path("personas/<int:pk>/programas", ProgramasUsuario.as_view({"get": "list"}), name=None),
    path("validar_datos_sicuc", RegistroCrear.as_view(), name=None), # se debe quitar
    path("personas/datos_app", DatosPersonaApp.as_view({"get": "list"}),name=None,),
    path("personas/actualizarqrs", ActualizarCodigosQr.as_view(),name=None,),
    path("personas/crearqrs", CrearCodigosQr.as_view({"get": "list"}),name=None,),
    path("personas/codigobarra", CrearBarracode.as_view({"get": "list"}),name=None,),
    path("personas/buscar_persona", buscarIdentidades.as_view({"post": "list"}),name=None,),
    path("personas/roles", RolesPersona.as_view({"get": "list"}),name=None,),
    #path("personas/masivo", CrearMasivos.as_view({"get": "list"}), name=None),
    path("personas/fotoMS", fotoMs, name=None),
    path("personas/encuesta_spa", EncuestaSPA.as_view({"post": "list"}), name=None),
    path("personas/encuesta_genero", ObtenerEncuestaGenero.as_view({"get": "list"}), name=None),
    path("personas/validar_encuesta_genero", ValidarEncuestaGenero.as_view(), name=None),
    path("personas/guardar_encuesta_genero", GuardarEncuestaGenero.as_view(), name=None),

    path("personas/validar_politica", ValidarPolitica.as_view(), name=None),
    path("personas/aceptar_politica", AceptarPolitica.as_view(), name=None)
]