"""
Django settings for facecuc project.

Generated by 'django-admin startproject' using Django 2.1.10.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import ast
from datetime import timedelta
from decouple import config
from rest_framework import permissions

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

CORS_ALLOWED_ORIGINS = [
    'https://emma.cuc.edu.co',
    'https://ovas.cuc.edu.co',
    'http://campusvirtualtest.cuc.edu.co',
    'http://localhost:3000',
]

CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-api-key',
    'x-csrftoken',
]

# CORS_ALLOW_CREDENTIALS = True
# CORS_EXPOSE_HEADERS = [
#     'Authorization',
# ]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    # 'microsoft_auth',
    'apps.genericas',
    'apps.personas',
    'apps.elecciones',
    'apps.practicas',
    'apps.inscripciones',
    'apps.internacionalizacion',
    'apps.grados',
    'apps.comentarios',
    'apps.becas',
    'apps.portal',
    'apps.matriculas',
    'apps.creditos',
    'apps.consultas',
    'apps.invitados',
    'apps.asistencia',
    'apps.reportes',
    'apps.retos',
    'apps.retoscuc',
    'apps.encuesta',
    'apps.rea',
    'apps.consultoria',
    'apps.validaciones',
    'apps.tutorias',
    'apps.autodiagnostico',
    'apps.apiOva',
    'apps.reporteVac',
    'apps.integracionesAPI',
    'apps.investigacion',
    'apps.invitadosVirtual',
    'apps.entrevistas',
    'apps.promocion',
    'apps.cursoformacion',
    'apps.inscripciones_posgrado',
    'apps.atencion',
    'corsheaders',
    'django_filters',
    'apps.bloques',
    'apps.centro',
    'apps.sisef',
    'apps.autogestion_estudiantil',
    # 'django.contrib.sites',
    # 'microsoft_auth',
]

AUTH_USER_MODEL = 'personas.Persona'

# msLogin
SITE_ID = 1
MICROSOFT_AUTH_LOGIN_ENABLED = True
MICROSOFT_AUTH_PKCE = True 
MICROSOFT_AUTH_LOGIN_TYPE = 'aad'
# MICROSOFT_AUTH_CLIENT_ID = '85622d00-244c-4044-8a8c-1dfb5895cc3e'
# MICROSOFT_AUTH_CLIENT_SECRET = 'QhU8Q~Fyvaoumix9XUIttIZS58mdcRt2J2EOkcAB'
# MICROSOFT_AUTH_TENANT_ID = "0507e5ce-0f95-49aa-abde-c90dcdedbd12" 
MICROSOFT_AUTH_CLIENT_ID = str(config("AZURE_CLIENT_ID")).strip()
MICROSOFT_AUTH_CLIENT_SECRET = str(config("AZURE_CLIENT_SECRET")).strip()
MICROSOFT_AUTH_TENANT_ID = str(config("AZURE_TENANT_ID")).strip()
MICROSOFT_REDIRECT_URI = str(config("REDIRECT_URI")).strip()

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PERMISSION_CLASSES' : (
        # 'rest_framework.permissions.IsAuthenticated',
        #'common.permissions.HavePermission'
    ),
    'DEFAULT_AUTHENTICATION_CLASSES' : (
        'rest_framework_simplejwt.authentication.JWTAuthentication' ,
        'rest_framework.authentication.SessionAuthentication' ,
        'rest_framework.authentication.BasicAuthentication' ,
    ),
}

# JWT_AUTH = {
#     'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=6),
#     'JWT_ALLOW_REFRESH': True,
#     'JWT_RESPONSE_PAYLOAD_HANDLER': 'facecuc.utils.my_jwt_response_handler',
#     'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(hours=12),
# }

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=6),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=6),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("JWT",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'microsoft_auth.middleware.MicrosoftAuthenticationMiddleware',
]

ROOT_URLCONF = 'facecuc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'facecuc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': config("ENGINE_BACK"),
        'NAME': config("NAME_BACK"),
        'USER': config("USER_BACK"),
        'PASSWORD': config("PASSWORD_BACK"),
        'HOST': config("HOST_BACK"),
        'PORT': config("PORT_BACK"),
        'OPTIONS': {
            'driver': config("DRIVER_BACK"),
        }
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'es'

# TIME_ZONE = 'UTC'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_URL = '/media/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
